import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers"; // Import the new providers wrapper

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Geeta Footwear",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png", // Add favicon path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Metadata defined above will be automatically used by Next.js */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>{children}</Providers> {/* Wrap children in Providers */}
      </body>
    </html>
  );
}
